<?php
namespace Tallakit\Parser;

require_once(__DIR__.'/../../TestCase.php');

/**
 * Test class for Grammar.
 * Generated by PHPUnit on 2011-04-04 at 17:49:32.
 */
class GrammarTest extends \Tallakit\TestCase
{
    /**
     * @var Grammar
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // FIXME $this->object = new Grammar(null); 
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testParse().
     */
    public function testParse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
